In [57]:
# Importando pandas
import pandas as pd


# Importando os dados para um dataframe
df = pd.read_csv('ocorrencia_2010_2020.csv', delimiter=';',
                 index_col='codigo_ocorrencia')


# Vendo as primeiras entradas
df.head()

                   codigo_ocorrencia1  ...  ocorrencia_saida_pista
codigo_ocorrencia                      ...
40211                           40211  ...                     NÃO
40349                           40349  ...                     NÃO
40351                           40351  ...                     NÃO
39527                           39527  ...                     NÃO
40324                           40324  ...                     NÃO

[5 rows x 21 columns]

Criar um dicionário apenas com as colunas que serão usadas e os nomes padronizados para cada uma dessas colunas.

In [58]:
# Selecionando as colunas e renomeando-as as que serão utilizadas, de fato
columns = {
    'ocorrencia_latitude': 'latitude',
    'ocorrencia_longitude': 'longitude',
    'ocorrencia_dia': 'data',
    'ocorrencia_classificacao': 'classificacao',
    'ocorrencia_aerodromo': 'aerodromo',
    'ocorrencia_cidade': 'cidade',
    'investigacao_status': 'status',
    'divulgacao_relatorio_numero': 'relatorio_numero',
    'total_aeronaves_envolvidas': 'aeronaves_envolvidas',
}

In [59]:
df = df.rename(columns=columns)
df.head()

                   codigo_ocorrencia1  ...  ocorrencia_saida_pista
codigo_ocorrencia                      ...
40211                           40211  ...                     NÃO
40349                           40349  ...                     NÃO
40351                           40351  ...                     NÃO
39527                           39527  ...                     NÃO
40324                           40324  ...                     NÃO

[5 rows x 21 columns]

In [60]:
# tentando dar um drop nas colunas codigo_ocorrencia1, ..., classificacao
df.drop(['codigo_ocorrencia1', 'codigo_ocorrencia2', 'codigo_ocorrencia3',
       'codigo_ocorrencia4'], axis=1, inplace=True)

In [61]:
df.head()

                  classificacao  ... ocorrencia_saida_pista
codigo_ocorrencia                ...
40211                 INCIDENTE  ...                    NÃO
40349                 INCIDENTE  ...                    NÃO
40351                 INCIDENTE  ...                    NÃO
39527                  ACIDENTE  ...                    NÃO
40324                 INCIDENTE  ...                    NÃO

[5 rows x 17 columns]

Converter o formato da coluna `data` para o formato `datetime`.

In [62]:
df.data = df.data + " " + df.ocorrencia_hora
df.data = pd.to_datetime(df.data)

In [63]:
# visualizando a conversao
df.data

codigo_ocorrencia
40211   2010-03-01 12:00:00
40349   2010-03-01 11:05:00
40351   2010-03-01 03:00:00
39527   2010-04-01 17:30:00
40324   2010-05-01 19:25:00
                ...
79804   2020-12-29 19:00:00
79757   2020-12-30 18:30:00
79802   2020-12-30 00:54:00
79756   2020-12-31 09:00:00
79844   2020-12-31 13:24:00
Name: data, Length: 5752, dtype: datetime64[ns]

Selecionar apenas as colunas que serão utilizadas no app do `Streamlit` (será o retorno da função `load_data()`).

In [64]:
df[list(columns.values())]

                         latitude  ... aeronaves_envolvidas
codigo_ocorrencia                  ...
40211                         ***  ...                    1
40349                         NaN  ...                    1
40351                         NaN  ...                    1
39527              -13.1066666667  ...                    1
40324                         NaN  ...                    1
...                           ...  ...                  ...
79804              -23.0069444444  ...                    1
79757                  -10.804722  ...                    1
79802                      -22.81  ...                    1
79756                  -22.507222  ...                    1
79844                    -22,9875  ...                    1

[5752 rows x 9 columns]

---

In [65]:
# Pega os diferentes tipos de classificação, sem repetição
df['classificacao'].unique()


# Converte para lsita
df['classificacao'].unique().tolist()

['INCIDENTE', 'ACIDENTE', 'INCIDENTE GRAVE']

In [66]:
lista_classificacao = list(df['classificacao'].unique())

In [67]:
labels = list(df.classificacao.unique())

labels

['INCIDENTE', 'ACIDENTE', 'INCIDENTE GRAVE']

In [68]:
df[(df.data.dt.year == 2017) & (df.classificacao.isin(['INCIDENTE']))]

                  classificacao  ... ocorrencia_saida_pista
codigo_ocorrencia                ...
66199                 INCIDENTE  ...                    NÃO
66250                 INCIDENTE  ...                    NÃO
66261                 INCIDENTE  ...                    NÃO
66271                 INCIDENTE  ...                    NÃO
66270                 INCIDENTE  ...                    NÃO
...                         ...  ...                    ...
77211                 INCIDENTE  ...                    NÃO
77208                 INCIDENTE  ...                    NÃO
77209                 INCIDENTE  ...                    NÃO
77205                 INCIDENTE  ...                    NÃO
77203                 INCIDENTE  ...                    NÃO

[231 rows x 17 columns]

In [97]:
dropando = df['longitude'] == '***'
df.replace(df['longitude'] = '***', 'NaN')
#print(sum(dropando), df['longitude'].shape[0])

SyntaxError: ignored

In [95]:
df['longitude']

codigo_ocorrencia
40211                ***
40349                NaN
40351                NaN
39527     -55.9930555556
40324                NaN
              ...
79804     -47.1344444444
79757         -49.756389
79802    -43.25055555555
79756         -54.364167
79844             -43,37
Name: longitude, Length: 5752, dtype: object

In [76]:
df.dtypes

classificacao                             object
latitude                                  string
longitude                                 object
cidade                                    object
ocorrencia_uf                             object
ocorrencia_pais                           object
aerodromo                                 object
data                              datetime64[ns]
ocorrencia_hora                           object
investigacao_aeronave_liberada            object
status                                    object
relatorio_numero                          object
divulgacao_relatorio_publicado            object
divulgacao_dia_publicacao                 object
total_recomendacoes                        int64
aeronaves_envolvidas                       int64
ocorrencia_saida_pista                    object
dtype: object